- src/Features/repositoryAPI.js
Har fixat API sök funktion. Endast repositoryAPI.js
searchFlix() - Async 
Parameters: (search String, multi Bool, page Int) 
search: the string to search for  
multi: if false it will only search for movies 
if true it will search for movies, tv shows and actors
page: the number of the page 
Returns a list of movies (20/page) matching a searchcriteria from db as JSON
JSON format: {"page": Int, "total_pages": Int, "total_results": Int, 
"id": Int,   
"title": String, 
"original_title": String, 
"original_language": String, 
"overview": String,
"poster_path": String, 
"release_date": Date,
"popularity": Int, 
"vote_average": Float,
"vote_count": Int,  
"video": Bool, 
"adult": Bool,
"backdrop_path": String, 
"media_type": String, 
"genre_ids": [Int, Int, Int] 
] 
} 
Usage:  
import { …
> API for search done

- README.md
- src/App.css
- src/App.js
- src/Components/ActiveView.jsx
- src/Components/GenreSidebar/GenreMenu.jsx
- src/Components/GenreSidebar/sidebarUi.css
Sidebar menu with all genres from genre API array. Fint?
> Tobias branch

- src/App.css
- src/App.js
- src/Components/BasketCounter.jsx
- src/Components/Footer.jsx
- src/Components/LoadingAnim.jsx
- src/Components/loadingAnim.css
- src/Features/genresListOf.js
- src/Features/repositoryAPI.js
Jag har lagt in top-level Css-Griden så att huvudfönstret inte kan växa sig större 1000px. Då bildas marginaler på sidorna.
ROBERT: Jag var tvungen att i Footern ändra positioneringar från "fixed" till "absolut" och dessutom lägga till "max-width: 1000px" och "min-width: 375px".
Jag har lagt upp sökvägarna till posters och backrundsbilder i session variabler. Jag har lagt upp tre storlekar av varje (Small, Medium och Large). se nedan.
Jag har lagt upp en API fråga för att få en lista kommande filmer (getUpcommingFlix()) ger dig 20 filmer per sida. se nedan.
Jag har lagt upp en API fråga för att få detaljerad info om en film (getFlixDetail()). Du får en hel skit-last med info. Dock inte skådespelare...
------------------------------------------------------------------
Session variables for …
> Mr movie lists api

- src/Components/ActiveView.jsx
- src/Components/GenreSidebar/GenreMenu.jsx
- src/Components/GenreSidebar/sidebarUi.css
Now the 'Genre' text won't scroll with the genres.
> Tob sidebar

- src/Components/BasketCounter/BasketCounter.jsx
- src/Components/Header/Header.css
- src/Components/LoginRegistration/LoginRegistration.css
- src/Components/LoginRegistration/LoginRegistration.jsx
- Förbättrad styling på login/registrering för att bättre efterlikna design
- Ny vy som visas efter lyckad registrering av ny användare
- Klicka på profilikonen för att få upp vy för login
- Klicka sen på text "New to WHS..." för att byta till vyn för registrering
- Efter att registrera en ny användare visas en tredje vy som hälsar användaren välkommen till WHS
- Knappen i tredje vyn (välkommen) är inte kopplad till någon navigation för tillfället (inväntar att en defaultvy är på plats)
> Post registration view and styling update

- package-lock.json
- package.json
- src/App.js
- src/Components/ActiveView/ActiveView.jsx
- src/Components/GenreSidebar/GenreMenu.jsx
- src/Components/GenreSidebar/sidebarUi.css
- src/Components/ShowGenreMovies/ChosenGenre.jsx
- src/Components/ShowGenreMovies/ChosenGenreUi.css
- src/Features/repositoryAPI.js
Fungerar, men visar bara en specifik genre som jag hårdkodat in i ChosenGenre.jsx.
> Tob branch

- src/Components/HomePage/HomePage.jsx
- src/Components/LoadingAnim/LoadingAnim.jsx
- src/Components/Search/Search.jsx
- src/Components/SearchResultRow/SearchResultRow.css
- src/Components/SearchResultRow/SearchResultRow.jsx
- src/Features/movieSelected.js
- src/Features/rootReducer.js
-Kolla så att redux koden ser ut som den ska i 'movieSelected'
-Säkerställa att redux State sätts till filmens ID när man klickar på 'placeholder' knappen på varje film
**Bra att veta** 
-just nu görs inte så mycket mer än att film ID loggas ut i console.
-Vissa fil/variable/knapp namn behövs ändras till tydligare namn
> Redux FilmID

- src/Components/ActiveView/ActiveView.jsx
- src/Components/SearchResultRow/SearchResultRow.jsx
- src/Components/SelectedMovie/SelectedMovie.css
- src/Components/SelectedMovie/SelectedMovie.jsx
- src/Features/activeView.js
- Hårdkodade värden för stunden men något att börja med
- Sök upp en film (genom sökfunktionen i footern) och klicka på den (valfri film vid fler träffar)
- Vyn för individuell film visas
- Alla värden är hårdkodade så behöver byggas upp genom ett API-anrop baserat på klickad film
> Individual movie

- src/Components/SelectedMovie/SelectedMovie.css
- src/Components/SelectedMovie/SelectedMovie.jsx
- Visar information som titel, beskrivning, bild mm.
- Klicka på valfri film från HomePage så visas filmen upp i vyn för SelectedMovie
- Fungerar endast från HomePage
- Något slår slint när man går genom sökfunktionen och film-id verkar inte skickas in i Redux
> Utökad funktion för SelectedMovie

- src/Components/SelectedMovie/SelectedMovie.jsx
- Faller tillbaka på nullvärde om bilden inte är redo
- Klicka på film från HomeScreen eller genom sökning
- Ingen röd console log ska visas vad gäller bildaddressen
> Rch bugfix movie poster 404

- src/Components/Search/Search.css
- src/Components/Search/Search.jsx
**Hur det fungerar**
- la till en 'previous' och en 'next' knapp  i 'search' som vid tryckning ändrar currPage till +/- 1 och laddar om searchResult
- gå in i search vyn (sök icon i footer) och sök på valfri term.
- Klicka på 'next' så ska currPage ändras till sig själv + 1(currPage syns mellan prev och next). Ska inte gå att ändra till högre än movie.total_pages
- Klicka på 'prev' så ska currPage ändras till sig själv - 1(currPage syns mellan prev och next). Ska inte gå att ändra till mindre än 1.
**Kvar att göra**
- lite styling. (t.ex att inte visa upp knapparna + currPage) om man inte har sökt på något.
> SearchResult pages func

- src/Components/GenreSidebar/GenreMenu.jsx
- src/Components/GenreSidebar/sidebarUi.css
- src/Components/ShowGenreMovies/ChosenGenre.jsx
Nu kan man gå in på individuell film från ChosenGenre. Lade också till så att man ser vilken genre man tryckt på.
**Test:** Tryck på en film i ChosenGenre.
> Indv movie chosen genre

- src/Components/GenreSidebar/GenreMenu.jsx
- src/Components/Search/Search.jsx
- src/Components/ShowGenreMovies/ChosenGenre.jsx
**vad som är fixat**
- fixat så varje Child i movieList.map har en unik key.
- tagit bort test logs 
- klicka på en genre i genre meny. Ska inte komma upp någon röd text eller logs i console.
> Stahre bugfix

- src/Components/ActiveView/ActiveView.jsx
- src/Components/Header/Header.jsx
- src/Components/HomePage/homePage.css
- src/Features/activeView.js
- src/Features/rootReducer.js
- src/Features/sideMenu.js
- Lyft bort sidomenyn helt ur Redux för ActiveView och istället skapat en separat Redux för den
- Städat upp koden i ActiveView.jsx
- Sidomenyn lägger sig över nuvarande aktiv vy, vid stängning ändras inte aktiv vy utan ligger istället kvar
- Behövde kommentera bort lite styling på HomePage som satte hela sidomenyn lite snett - tittar på bättre fix framöver
> Sidemenu adjustment

- src/Components/ActiveView/ActiveView.jsx
- src/Components/Footer/Footer.jsx
- src/Components/GenreSidebar/GenreMenu.jsx
- src/Components/Header/Header.jsx
- src/Components/SelectedMovie/SelectedMovie.jsx
- Också städat en del oanvänd kod
- Öppna sidomenyn, välj en genre - menyn ska stängas och vald genre visas
> Stängbar sidomeny

- src/Features/repositoryAPI.js
Ändrade sökkriterier från 3000 röster på en film till 100 röster. Så nu får vi även upp "Documentary"
> Changed searchcriteria in getGenreMovieList- vout_count.gte=100

- src/Components/GenreSidebar/GenreMenu.jsx
- src/Components/Search/Search.jsx
- src/Components/ShowGenreMovies/ChosenGenre.jsx
- src/Features/genreSelected.js
- gå in i en genre, klicka på next(ska inte gå att ändra den längre än total_pages)
- gå in i en genre, klicka på back(ska inte gå att ändra den under 1)
- gå in i en genre, klicka på next ett par gånger, gå sedan in i en ny genre. sidan som visas upp ska vara first page.
> Kan inte bläddra längre än total pages och man startar alltid på first page när man går in i en genre + Code cleanup

- src/Components/BasketView/BasketView.css
- src/Components/BasketView/BasketView.jsx
- src/Components/SelectedMovie/SelectedMovie.jsx
- src/Features/customerBasket.js
- src/Features/rootReducer.js
- Redux för kundvagn med funktion för att lägga till och ta bort produkter
- Omvandlar värdet i redux till grafik i basketView.jsx
- Lägg till valfri(a) film(er) genom att gå in på en film och klicka "Buy"
- Klicka på kundvagnen för att gå till översikten för kundvagnen där samtliga filmer bör återfinnas
- Totalsumman av alla filmer visas under filmerna
- Vid klick på respektive kryss raderas filmen från kundvagnen och totalvärdet uppdateras
- Eventuellt spara kundvagnen i localStorage så den behålls när man uppdaterar sidan
> Kundvagnslogik

- src/Components/BasketCounter/BasketCounter.css
- src/Components/BasketCounter/BasketCounter.jsx
- src/Components/BasketView/BasketView.css
- src/Components/BasketView/BasketView.jsx
- src/Components/Header/Header.css
- src/Components/Header/Header.jsx
- src/Components/SelectedMovie/SelectedMovie.css
- src/Components/SelectedMovie/SelectedMovie.jsx
- När film läggs i kundvagnen visas nu animering på köpknappen samt en bubbla vid varukorgen visas med antal filmer i varukorgen
- Lägg en film i varukorgen så visas antal filmer i varukorgen (i en bubbla vid varukorgsknappen)
- Antal uppdateras både vid nya filmer och när filmer raderas ur varukorgen
- Om varukorgen är tom så visas inte bubbklan
> Effekter vid köp

- src/Components/SelectedMovie/SelectedMovie.css
- src/Components/SelectedMovie/SelectedMovie.jsx
**hämtar IMDB rating från API och visar up. Finns ingen rating visas ett meddelande upp istället.**
- Gå in på valfri film. Har filmen en rating så ska det visas upp under "IMDB rating". t.ex "7.6/10"
- Finns det ingen IMDB rating(t.ex pga att filmen är ny eller inte har kommit ut) ska det stå "No rating found" istället.
> visa upp film IMDB rating

- src/Components/ActiveView/ActiveView.jsx
- src/Components/BasketView/BasketView.jsx
- src/Components/Checkout/CheckoutThanks.css
- src/Components/Checkout/CheckoutThanks.jsx
- src/Components/Checkout/CheckoutView.css
- src/Components/Checkout/CheckoutView.jsx
- src/Features/activeView.js
Fixade css bug med max width på Checkout och viewn efter.
> Tob checkout

- package-lock.json
- package.json
- Projektet kan nu läggas upp på rchorngren.github.io/whs
- Läggs upp med kommano i terminalen 'npm run deploy'
- Inte mycket att testa (tror inte alla ska köra npm run deploy samtidigt) men ni hittar en testdeploy [här](https://rchorngren.github.io/whs/)
> Github pages deployment

- src/Components/ActiveView/ActiveView.jsx
- src/Components/ProfileOrder/ProfileOrder.jsx
- src/Components/ReviewView/ReviewView.css
- src/Components/ReviewView/ReviewView.jsx
- src/Features/activeView.js
grafiken för att lämna en review är nu på plats.
- logga in och gå till order history. 
- Klicka placeholder knappen för att visa upp leave a review View.
- skriv lite text och klicka i checkboz(ska inte gå att kunna submit om checkbox inte är i klickad)
- Thanks for your review View ska visas upp.
- trycker man på go back knappen ska man komma tillbaka till att lämna en review.
**kvar att göra**
- införa all logic 
- om checkbox inte är i klickad, visa ett meddelande
- go back knappen kanske ska skicka användaren tillbaka till order history istället för review?(kom på det medans jag skrev PR)
> added graphics for leaving a review

- src/Components/BasketView/BasketView.jsx
- src/Components/Checkout/CheckoutView.jsx
- src/Components/OrderhistoryView/OrderhistoryView.css
- src/Components/OrderhistoryView/OrderhistoryView.jsx
- src/Components/ProfileOrder/ProfileOrder.jsx
- src/Features/customerBasket.js
- src/Features/repositoryFS.js
- Inkluderar även tömning av kundvagn efter avslutat köp
- Lägg film(er) i varukorgen och gå till kassan
- Klicka 'proceed to checkout' och sen 'pay' för att slutföra köpet
- Beställningen med filmerna dyker upp i Firebase
- Lägga till spärr på 'proceed to checkout' om varukorgen är tom (så man inte försöker lägga en tom order)
> Köpfunktion

- src/Components/Checkout/CheckoutView.jsx
- src/Components/OrderhistoryView/OrderhistoryView.jsx
- src/Components/ProfileOrder/ProfileOrder.jsx
- src/Components/ReviewView/ReviewView.css
- src/Components/ReviewView/ReviewView.jsx
- Logga in och gå till order History
- Klicka på placeholder knappen för att komma till review view
- hover över stars för att temporärt fylla i dom, ta bort hover för att ta bort fylling
- Klicka på en star för att fylla i den + de stars som kommer före.
-  ska inte gå att trycka submit om inte minst 1 star är i fylld
> Star rating styling

- src/Components/Checkout/CheckoutView.jsx
- src/Components/OrderhistoryView/OrderhistoryView.css
- src/Components/OrderhistoryView/OrderhistoryView.jsx
- src/Components/ProfileOrder/ProfileOrder.css
- src/Components/ProfileOrder/ProfileOrder.jsx
- src/Components/ReviewView/ReviewView.jsx
- src/Features/movieToReview.js
- src/Features/repositoryFS.js
- src/Features/rootReducer.js
- Visar samtliga tidigare beställningar med orderdatum, filmer på beställningen och totalpris
- Varje film är klickbar för att länka vidare till vy för att lämna omdöme
- Logga in, klicka på profil och välj sen fliken 'order history'
- Efter viss laddningstid visas orderhistorik (finns inga beställningar visas istället en text för det)
- Varje film är klickbar och länkas till ReviewView. Movieid skickas även dit genom Redux för fortsatt utveckling för att lämna omdömme
- På ReviewView finns en kvarlämnad console.log för att visa id på den film man klickat på, detta för att underlätta fortsatt utveckling till en början
> Orderhistorik

- src/Components/Checkout/CheckoutThanks.css
- src/Components/Checkout/CheckoutThanks.jsx
- src/Components/Checkout/CheckoutView.css
- src/Components/Checkout/CheckoutView.jsx
- src/Components/GenreSidebar/GenreMenu.jsx
Gjorde animation så att texten förminskas när man clickar på "Pay" och "Thanks".
**Test:** Clicka på "Pay" efter proceed to checkout i kundvagnen, sen "Thanks".
Kvar att göra: GenreMenu, att man kan clicka på en genre med animation.
> Tob purchase buttons

- src/Components/GenreSidebar/GenreMenu.jsx
- src/Components/GenreSidebar/sidebarUi.css
Lade till så att texten blir blå i genre menyn när man clickar på den och :hover när man är i desktop.
**Test:** Clicka på genres i genre menyn.
> Tob genre menu on click

- src/Components/ReviewView/ReviewView.css
- src/Components/ReviewView/ReviewView.jsx
Användaren kan nu lämna en review och det sparas till Firebase.
-  Logga in och gå till order history. Klicka på en film du vill lämna en review på.
-  fyll i text rutan, lämna en rating och klicka i checkboxen. Tryck submit(har man inte fyllt i något av text, rating eller checkbox ska en varningstext visas och man skickas inte vidare).
-  Kolla med marek om din review syns i firebase
> Stahre review logik

- src/Components/BasketView/BasketView.css
- src/Components/BasketView/BasketView.jsx
- src/Components/Checkout/CheckoutView.jsx
- src/Components/HomePage/HomePage.jsx
- Grundläggande regex för att kontrollera värden i inputs vid köp (email, kortinnehavare, kortnummer, ccs och datum)
- För att slutföra köp måste alla fält vara korrekt ifyllda
- Vid fel värde visas felmeddelande i köpknappen tillfälligt (försvinner efter fem sekunder)
- Vid tom kundvagn kan man inte längre gå vidare till kassan
- Lägg film i kundvagnen och klicka på varukorgen, klicka sen på 'proceed to checkout' (om varukorgen är tom är knappen inaktiverad)
- Om ett fält är inkorrekt ifyllt visas felmeddelande en kort stund
- Om alla fält är korrekt ifyllda går beställningen igenom och hittas sen i orderhistoriken
Hur inputs fylls i korrekt:
- Email kräver en korrekt emailadress
- Card holder kräver en sträng med bokstäver
- Card number och CCV godkänner endast siffor
- Valid until …
> Regex vid köp mm.

- src/Components/SelectedMovie/SelectedMovie.css
- src/Components/SelectedMovie/SelectedMovie.jsx
**hur man testar**
- klicka in på valfri film
- finns det en review så ska det synas en ruta med user review och rating
- finns det ingen review så visas det upp en ruta med 'There are no user reviews yet'
> display users reviews on movie page

- src/Components/LoginRegistration/LoginRegistration.jsx
- src/Components/SelectedMovie/SelectedMovie.jsx
- Om inga omdömen finns visas IMDB rating
- Annars visas WHS egna omdöme
- Gå in på t.ex. filmen Cruella som har omdöme, WHS egna omdöme visas
- Gå in på Gudfadern 2, som inte har omdöme. IMDBs omdöme visas
- Man kan inte se IMDB och WHS omdöme samtidigt
> WHS genomsnittsomdöme

- src/Components/ActiveView/ActiveView.jsx
- src/Components/HomePage/HomePage.jsx
- src/Components/Search/Search.jsx
- src/Components/SearchResultRow/SearchResultRow.css
- src/Components/SearchResultRow/SearchResultRow.jsx
- src/Components/SelectedPerson/SelectedPerson.css
- src/Components/SelectedPerson/SelectedPerson.jsx
- src/Features/activeView.js
- src/Features/repositoryAPI.js
- src/Features/repositoryFS.js
- Hittar skådespelare i sökfunktionen
- Tar upp en info-sida om skådespelare
- Info-sidan listar även filmer med skådespelaren - klickbara
- En ny funktion i repositoryAPI.js, getPersonDetail(dispatch, id, page). Se repositoryAPI för mer info.
1. Använd sökfunktionen, sök efter tex John Belushi
2. Välj skådespelare
3. Testa och klicka på en film 
- Rensa bort irrelevant data (icke skådisar)
- Eller ta hand om dessa (sök på crew)
- Sidhantering för filmer
Inga
> Mr actor search
